import { describe, expect, it } from "vitest";
import {
  applyParams,
  armLengths,
  createWorld,
  resetWorld,
  simulate,
} from "./workerCore";
import {
  DEFAULT_PHYSICS_PARAMS,
  GHOST_COUNT,
  GHOST_OFFSET,
  STRIDE,
} from "./types";
import {
  makeOraclePendulum,
  oracleSnapshot,
  oracleStepPendulum,
} from "../tests/oracle";

const SIZE = 800;

/**
 * Golden values generated by scripts/generate-goldens.mjs — an independent
 * verbatim copy of the original index.html math. AGENTS.v2.md Phase 4
 * acceptance criterion.
 */
const GOLDEN_STEP_1 = {
  a1: 3.14159236894,
  a2: 0.392696924983,
  a1v: -0.0000037953285391,
  a2v: -0.0000287561930756,
  x1: 400.000150295,
  y1: -128,
  x2: 501.028050407,
  y2: 115.904414472,
};

const GOLDEN_STEP_100 = {
  a1: 3.13874099973,
  a2: 0.37125910204,
  a1v: -0.00038085422869,
  a2v: -0.00284161403041,
  x1: 401.505671196,
  y1: -127.997853172,
  x2: 497.281977829,
  y2: 118.016168964,
};

/** The streamed buffer is Float32Array by design — quantize expectations. */
const f32 = (v: number) => Math.fround(v);

function extractStep(buffer: Float32Array, step: number, pendulum = 0) {
  const base = (step * 1 + pendulum) * STRIDE;
  return {
    a1: buffer[base],
    a2: buffer[base + 1],
    a1v: buffer[base + 2],
    a2v: buffer[base + 3],
    x1: buffer[base + 4],
    y1: buffer[base + 5],
    x2: buffer[base + 6],
    y2: buffer[base + 7],
  };
}

describe("physics golden values (original parity)", () => {
  it("matches the original after 1 step", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    const { buffer } = simulate(world, 1);
    const got = extractStep(buffer, 0);
    for (const key of Object.keys(GOLDEN_STEP_1) as (keyof typeof GOLDEN_STEP_1)[]) {
      expect(got[key]).toBe(f32(GOLDEN_STEP_1[key]));
    }
  });

  it("matches the original after 100 steps", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    const { buffer } = simulate(world, 100);
    const got = extractStep(buffer, 99);
    for (const key of Object.keys(GOLDEN_STEP_100) as (keyof typeof GOLDEN_STEP_100)[]) {
      expect(got[key]).toBe(f32(GOLDEN_STEP_100[key]));
    }
  });
});

describe("differential test vs original oracle (bitwise)", () => {
  it("reproduces the oracle trajectory exactly over 500 steps", () => {
    const steps = 500;
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    const { buffer } = simulate(world, steps);

    const [l1, l2] = armLengths(world);
    const oracle = makeOraclePendulum(
      DEFAULT_PHYSICS_PARAMS.a1Init,
      DEFAULT_PHYSICS_PARAMS.a2Init,
      l1,
      l2
    );
    const masses = {
      g: DEFAULT_PHYSICS_PARAMS.g,
      m1: DEFAULT_PHYSICS_PARAMS.m1,
      m2: DEFAULT_PHYSICS_PARAMS.m2,
    };

    for (let s = 0; s < steps; s++) {
      oracle.l1 = l1;
      oracle.l2 = l2;
      oracleStepPendulum(oracle, masses);
      const expected = oracleSnapshot(oracle, SIZE);
      const got = extractStep(buffer, s);
      for (const key of Object.keys(expected) as (keyof typeof expected)[]) {
        expect(got[key]).toBe(f32(expected[key]));
      }
    }
  });

  it("reproduces ghost trajectories exactly (6 pendulums, θ₁ offset i·0.002)", () => {
    const steps = 200;
    const world = createWorld(
      { ...DEFAULT_PHYSICS_PARAMS, multi: true },
      SIZE
    );
    const { buffer, pendulums } = simulate(world, steps);
    expect(pendulums).toBe(GHOST_COUNT);

    const [l1, l2] = armLengths(world);
    const masses = {
      g: DEFAULT_PHYSICS_PARAMS.g,
      m1: DEFAULT_PHYSICS_PARAMS.m1,
      m2: DEFAULT_PHYSICS_PARAMS.m2,
    };
    const oracles = Array.from({ length: GHOST_COUNT }, (_, i) =>
      makeOraclePendulum(
        DEFAULT_PHYSICS_PARAMS.a1Init + i * GHOST_OFFSET,
        DEFAULT_PHYSICS_PARAMS.a2Init,
        l1,
        l2
      )
    );

    for (let s = 0; s < steps; s++) {
      for (let i = 0; i < GHOST_COUNT; i++) {
        const oracle = oracles[i];
        oracle.l1 = l1;
        oracle.l2 = l2;
        oracleStepPendulum(oracle, masses);
        const expected = oracleSnapshot(oracle, SIZE);
        const base = (s * GHOST_COUNT + i) * STRIDE;
        expect(buffer[base]).toBe(f32(expected.a1));
        expect(buffer[base + 1]).toBe(f32(expected.a2));
        expect(buffer[base + 2]).toBe(f32(expected.a1v));
        expect(buffer[base + 3]).toBe(f32(expected.a2v));
        expect(buffer[base + 4]).toBe(f32(expected.x1));
        expect(buffer[base + 5]).toBe(f32(expected.y1));
        expect(buffer[base + 6]).toBe(f32(expected.x2));
        expect(buffer[base + 7]).toBe(f32(expected.y2));
      }
    }
  });
});

describe("workerCore behavior", () => {
  it("produces a correctly sized batch for speed > 1", () => {
    const world = createWorld({ ...DEFAULT_PHYSICS_PARAMS, speed: 4 }, SIZE);
    const { buffer, steps, pendulums } = simulate(world, world.params.speed);
    expect(steps).toBe(4);
    expect(pendulums).toBe(1);
    expect(buffer.length).toBe(4 * 1 * STRIDE);
  });

  it("returns an empty batch when paused", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE, false);
    // The worker derives the step count from `running` (worker.ts tick case);
    // simulate() itself is a pure stepper.
    const { buffer, steps } = simulate(
      world,
      world.running ? world.params.speed : 0
    );
    expect(steps).toBe(0);
    expect(buffer.length).toBe(0);
  });

  it("counts total steps across batches", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    simulate(world, 3);
    simulate(world, 5);
    expect(world.totalSteps).toBe(8);
  });

  it("applyParams applies live params on the next step", () => {
    const base = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    const changed = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    applyParams(changed, { g: 0.25 });
    simulate(base, 10);
    simulate(changed, 10);
    expect(extractStep(simulate(base, 1).buffer, 0).a1).not.toBe(
      extractStep(simulate(changed, 1).buffer, 0).a1
    );
  });

  it("toggling multi re-initializes immediately", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    simulate(world, 10);
    applyParams(world, { multi: true });
    expect(world.pendulums.length).toBe(GHOST_COUNT);
    expect(world.totalSteps).toBe(0);
    // Initial states match the original ghost seeding (index.html:610–617):
    // ghost i starts at a1Init + i·0.002.
    for (let i = 0; i < GHOST_COUNT; i++) {
      expect(world.pendulums[i].a1).toBe(
        DEFAULT_PHYSICS_PARAMS.a1Init + i * GHOST_OFFSET
      );
      expect(world.pendulums[i].a2).toBe(DEFAULT_PHYSICS_PARAMS.a2Init);
      expect(world.pendulums[i].a1v).toBe(0);
      expect(world.pendulums[i].a2v).toBe(0);
    }
  });

  it("initial angles only take effect after reset", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, SIZE);
    simulate(world, 10);
    applyParams(world, { a1Init: Math.PI / 2 });
    let { buffer } = simulate(world, 1);
    expect(buffer[0]).not.toBeCloseTo(Math.PI / 2, 12);
    resetWorld(world);
    ({ buffer } = simulate(world, 1));
    // After one step from π/2 the angle has moved slightly off π/2
    expect(buffer[0]).toBeLessThan(Math.PI / 2 + 0.001);
    expect(buffer[0]).toBeGreaterThan(Math.PI / 2 - 0.001);
  });

  it("changing size scales arm lengths", () => {
    const world = createWorld(DEFAULT_PHYSICS_PARAMS, 800);
    expect(armLengths(world)).toEqual([528, 264]);
    world.size = 400;
    expect(armLengths(world)).toEqual([264, 132]);
  });
});
